### ISSUE TITLE
Update repositories action broken

### ISSUE THREAD

**Issue by otjamin** [linux-surface/repo#13]
Hey everyone,
unfortunately the repo update action seems to be broken since a week.

I don't know if this is related, but the libwacom-surface package is missing in the Fedora 41 repo.

Hope you can fix this. Thanks for your efforts. :blue_heart: 

EDIT:
The job failed on `2024-10-25T00:43:36.1892947Z fatal: unable to access 'https://github.com/linux-surface/repo.git/': Failed to connect to github.com port 443 after 135239 ms: Could not connect to server`.
Was possibly just a temporary problem.

But now it fails because the `u/hold` branch did not get removed.

**Comment by otjamin** [comment]
https://github.com/linux-surface/linux-surface/issues/1578

**Comment by qzed** [comment]
Yeah, there are occasional random hiccups. I just haven't gotten around to remove `u/hold` (but that shouldn't have really impacted anything because I also haven't gotten around to push new updates since it failed). Anyway, the repo update actions are running again and I'll have a look at libwacom for fedora 41 now.
