### ISSUE TITLE
Use metapackages for Debian/Ubuntu

### ISSUE THREAD

**Issue by danielzgtg** [linux-surface/repo#2]
The `linux-image-surface` package should use a metapackage like how Debian/Ubuntu do for the official `linux-image-generic`.

Using a metapackage would let users update their systems without worrying that their system becomes unbootable. While a broken userland could be troubleshooted with `init=/bin/bash`, a broken kernel needs a working kernel to fix. The metapackage would allow multiple kernels, especially the previously working kernel, to be installed at the same time.

The metapackage would look like this: `linux-image-surface` would not contain any files but rather depend on `linux-image-5.5.10-surface`. `linux-image-5.5.10-surface` and `linux-image-5.5.9-surface` would contain the actual files and be installable side-by-side.

**Comment by qzed** [comment]
We've initially looked at using the Debian kernel build files to reproduce the Debian package structure, however, it turns out that we can't reliably use them for the kernel versions we want to provide (as Debian is generally behind in versions) without some major modifications that would require additional maintenance.

Meta-packages could (and in our case should) be done without that, however, it's not something that I want to spend time on right now. If someone else want's to take this up, be my guest.

At the moment I think we're in a state where if you have any issues with the surface kernel installation you can always use the stock kernel to install the last version that worked for you, or if you're concerned install LTS and latest in parallel.

**Comment by danielzgtg** [comment]
Closing as discussion seems to have become centralized at #3 instead.
