### ISSUE TITLE
Provide linux-surface-keyring for Archlinux

### ISSUE THREAD

**Issue by shih-liang** [linux-surface/repo#7]
It would be nice if `linux-surface-keyring` is provided for Arch Linux. It can free the users from the burden of key management and it's easy to implement, To write PKGBUILD and linux-surface-keyring.install, the following modified from official Arch Linux repo can be used as a reference,:

PKGBUILD:
```
pkgname=linux-surface-keyring
pkgver=1
pkgrel=1
pkgdesc='Linux Surface PGP keyring'
arch=(any)
url='https://github.com/linux-surface/linux-surface/'
license=(GPL)
install=$pkgname.install
source=('linux-surface.gpg::https://raw.githubusercontent.com/linux-surface/linux-surface/master/pkg/keys/surface.asc')
sha256sums=('SKIP')
validpgpkeys=('SKIP')

package() {
  echo "87DEFA4AB94A99A4C8C3112556C464BAAC421453:4:" > linux-surface-trusted
  export PREFIX=/usr
  export DESTDIR="$pkgdir"
  install -dm755 ${DESTDIR}${PREFIX}/share/pacman/keyrings/
  install -m0644 linux-surface.gpg ${DESTDIR}${PREFIX}/share/pacman/keyrings/
  install -m0644 linux-surface-trusted ${DESTDIR}${PREFIX}/share/pacman/keyrings/
}
```

.install
```
post_upgrade() {
	if usr/bin/pacman-key -l >/dev/null 2>&1; then
		usr/bin/pacman-key --populate linux-surface
		usr/bin/pacman-key --updatedb
	fi
}

post_install() {
	if [ -x usr/bin/pacman-key ]; then
		post_upgrade
	fi
}
```

**Comment by StollD** [comment]
I am not that experienced with Arch, so what would this improve?

If we package up the GPG key we kinda run into the chicken / egg problem: We cant use our signing key to sign the package that installs the signing key. We cant sign it with another trusted key either, because we dont have access to one.

We also never actually changed the signing key, so after you import it during first setup you should be good to go.

**Comment by qzed** [comment]
> I am not that experienced with Arch, so what would this improve?

This would remove the need for importing the GPG key manually, i.e. the steps on the wiki could be replaced by "add repo to pacman.conf and install this package".

> If we package up the GPG key we kinda run into the chicken / egg problem: We cant use our signing key to sign the package that installs the signing key. We cant sign it with another trusted key either, because we dont have access to one.

Actually, adding this package to the repo doesn't make any sense at all for us right now. If you have not imported the key that's currently being used to sign the repo, pacman will abort. Just tested this and `pacman -Syu` after adding the repo fails with
```
:: Synchronizing package databases...
 core is up to date
 extra is up to date
 community is up to date
 linux-surface                                                                      6.6 KiB  24.8 KiB/s 00:00 [#################################################################] 100%
error: linux-surface: key "87DEFA4AB94A99A4C8C3112556C464BAAC421453" is unknown
:: Import PGP key 87DEFA4AB94A99A4C8C3112556C464BAAC421453? [Y/n] y
error: linux-surface: signature from "Linux-Surface Package Signer (signing-key for packages in linux-surface package repositories) <luzmaximilian@gmail.com>" is unknown trust
error: failed to synchronize all databases (invalid or corrupted database (PGP signature))
```

A package like this makes sense when you manage multiple keys. We don't. So if we would change the key, pacman would fail again because the new key would be unknown and the package couldn't be updated due to that.

I think at best this package makes sense in AUR (as helper to simplify installation and reduce steps) or as standalone PKGBUILD. In both cases, it avoids the signing problem. I kind of prefer being explicit about you adding and trusting a new key in our installation guide though.

**Comment by shih-liang** [comment]
Keyring packages helps a lot when multiple keys used or any changes in keys. If only one key is used and never changed, the two ways mightn't have much difference. This may be Linux-surface repo's case, I'll close this issue.

For the chicken / egg problem, by the way, if I recall it correctly, pacman doesn't seem to check the sig of local files by default. So the keyring package can be signed by any key or not be signed at all as long as it is downloaded and installed separately.

Comparing with manually downloading keys, I think sharing keys via key server is more preferable, and it's supported by pacman and some other package managers.
